### PR TITLE
I can't pass the null object to JS with ResultHelper.Set<T>() function.

### PR DESCRIPTION
**Pull request by cheolhui-lee**
Hello,

When I used ResultHelper.Set<T>() function, I can't pass the null value to JS.
Because of "Set<T>" function is generic, and It didn't allow the nullable.
For example, I called a _Set_ funtion with null value like below code.
`Puerts.ResultHelper.Set((int)data, isolate, info, null);`

But the last _null_ parameter is not null in the **Set** function.
```
public static void Set<T>(int jsEnvIdx, IntPtr isolate, IntPtr info, T result)
{
    // 'result' is not a null. It is default of T.
    StaticTranslate<T>.Set(jsEnvIdx, isolate, NativeValueApi.SetValueToResult, info, result);
}
```

So, I need to change the code for explicitly pass <null or not> together.
```
public static void Set<T>(int jsEnvIdx, IntPtr isolate, IntPtr info, T result, bool isNullValue = false)
{
    // Generic function issue.
    // If pass the null value to the generic function, the parameter is not null and it is a default value.
    // Explicitly pass <null or not> together. (isNullValue)
    if (isNullValue)
    {
        // TODO : need to make a code in a prettier way.
        Set(jsEnvIdx, isolate, info, Puerts.JsValueType.NullOrUndefined);
    }
    else
    {
        StaticTranslate<T>.Set(jsEnvIdx, isolate, NativeValueApi.SetValueToResult, info, result);
    }
}
```

It is helpful for Unity developers.

For example,
When someone generated wrapper code for GameObject before.
If the person call GetComponent(A) to GameObject that doesn't contain the A component,
That function will be return exact null and it can check component by null in JS.

So, please check the issue.
Thanks.

### CODE REVIEW

**Comment by zombieyang** [comment]
Could you provide a testcase for this problem?
in https://github.com/Tencent/puerts/blob/master/unity/general/Src/UnitTest/UnitTest.cs or https://github.com/chexiongsheng/puerts_unity_demo

**Comment by cheolhui-lee** [comment]
I prepared samples for this issue in my fork repository that is from puerts_unity_demo.
[https://github.com/cheolhui-lee/puerts_unity_demo](https://github.com/cheolhui-lee/puerts_unity_demo)

**Comment by zombieyang** [comment]
the reason why result of GetComponent<Light>() is null, is that UnityEngine override the '==' operator of UnityEngine.Object. you can learn some information in the [FAQ of XLua](https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E6%9C%89%E7%9A%84unity%E5%AF%B9%E8%B1%A1%E5%9C%A8c%E4%B8%BAnull%E5%9C%A8lua%E4%B8%BA%E5%95%A5%E4%B8%8D%E4%B8%BAnil%E5%91%A2%E6%AF%94%E5%A6%82%E4%B8%80%E4%B8%AA%E5%B7%B2%E7%BB%8Fdestroy%E7%9A%84gameobject).

So, we think it is not a business of NullableType. And the best experience for this case is to define a CS function which can check a value is`== null` or not. And then expose it to JS (just like what xLua FAQ recommended to do).

**Comment by cheolhui-lee** [comment]
If return value is not null when developer expect that is null, then they can be confused.
Especially now, our Unity developers are confused about that.
So focusing the null, I thought it's intuitive to pass the null of javasciprt when the null of c# is passed to Javascript.

Your opinion is acceptable, but I think '==' or '===' is more helpful way for developers who without knowing it.
Even if my PR code is not exactly the right way and maybe it is not important feature, I want you to consider this issue.
Thanks.

**Comment by chexiongsheng** [comment]
GetComponent for a not exist Component, Unity do not return a null;
it return a not null C# object with specific state.
UnityEngine.Object override the == operator to return true when you compare this obj with null.
to solve this problom, you mush write a compare method in c#， and call it to check the state of Component.
`
    public static bool IsNull(this UnityEngine.Object o) 
    {
        return o == null;
    }
`

**Comment by zombieyang** [comment]
> If return value is not null when developer expect that is null, then they can be confused.
> Especially now, our Unity developers are confused about that.
> So focusing the null, I thought it's intuitive to pass the null of javasciprt when the null of c# is passed to Javascript.
> 
> Your opinion is acceptable, but I think '==' or '===' is more helpful way for developers who without knowing it.
> Even if my PR code is not exactly the right way and maybe it is not important feature, but I want you to consider this issue.
> Thanks.

Thanks for your advice. 
I tried to override `===` or `==` behaviour of JSValue. But it seems like in Javascript there is no way to do that...
Some similiar way is override the `+` behaviour by modifying `ValueOf()` or using `toString()`. But I think these are not helpful.

We will add some tips in FAQ first and think about it in the future.

**Pull request closed without merging**
